name: Lint & Test

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-test:
    runs-on: ubuntu-latest
    env:
      MAINNET_URL: https://eth-mainnet.alchemyapi.io/v2/CDf_84N-bbVsyODpzmL_ahJwyrZvsTb7
      BLOCK_NUMBER: 14391300
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Compile
        run: yarn compile
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
