name: Commitlint Lint Test & Build

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  commitlint-lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install
        run: yarn install
      - name: Compile
        run: yarn compile --force
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
